/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "#050510",
        secondary: "#0A0F1E",
        elevated: "#111827",
        accent: "#00FF88",
        "accent-pink": "#FF2D55",
        purple: "#7C3AED",
        cyan: "#06B6D4",
        amber: "#F59E0B",
        "text-primary": "#F8FAFC",
        "text-secondary": "#94A3B8",
        "text-muted": "#64748B",
        success: "#10B981",
        error: "#EF4444",
        warning: "#F59E0B",
        border: "rgba(255,255,255,0.08)",
        glass: "rgba(255,255,255,0.05)",
        "glass-border": "rgba(255,255,255,0.1)",
        // Legacy tokens
        foreground: "#F8FAFC",
        muted: "#111827",
        "muted-foreground": "#64748B",
        "accent-foreground": "#000000",
      },
      fontFamily: {
        space: ["SpaceGrotesk", "sans-serif"],
        mono: ["SpaceMono", "monospace"],
        inter: ["Inter", "sans-serif"],
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "40px",
      },
      fontSize: {
        "title-lg": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "title-md": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        body: ["16px", { lineHeight: "24px", fontWeight: "400" }],
        caption: ["13px", { lineHeight: "18px", fontWeight: "400" }],
        tiny: ["11px", { lineHeight: "14px", fontWeight: "400" }],
      },
      borderRadius: {
        none: "0px",
        sm: "4px",
        DEFAULT: "12px",
        md: "12px",
        lg: "16px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
